### ISSUE TITLE
NO "trace_replay_seg" and "trace_replay_seg" found after building.

### ISSUE THREAD

**Issue by DaokunHu** [Thesys-lab/Segcache#1]
After building, in **build/bin** there are just 
![image](https://user-images.githubusercontent.com/13998202/144979107-3e2e66c1-8582-4bd0-a016-605dfa8a2afb.png)

But **pelikan_segcache** doesn't recognize  **trace_replay_seg.conf**
The output for  "$ ./pelikan_segcache trace_replay_seg.conf" is
> load config from trace_replay_seg.conf
error loading config line: no option named 'debug_logging'
failed to load config

**Comment by 1a1a11a** [comment]
Hi, thank you for the issue. The trace replay tool is under benchmarks. :)
