### ISSUE TITLE
Some questions about configurations in experiment setup

### ISSUE THREAD

**Issue by DaokunHu** [Thesys-lab/Segcache#2]
Thanks for your nice work!.
Could you please offer an example of the configurations in the experiment setup? Here are some concerns:
* Large size and small size for workloads **c,u1,u2,n,mix**  in Fig.6  
* HASH_POWER

Besides, is there any way to print the number of merged segments after an evaluation?

Thanks for your patience.
Looking forward to your reply.

**Comment by 1a1a11a** [comment]
I don't have the exact config at this time, but it should not be hard to find by running at a few sizes, I think the max size of c is 1-8GB (do not remember exactly), and the max size for u1, u2 and n are small (<1GB, maybe 256 MB). The correct choice of hash power does not have any impact on miss ratio nor throughput, try 25 and increase with cache size (there is little penalty of using a large hash power except the hash table uses more DRAM).

**Comment by DaokunHu** [comment]
Thanks for your help!
