### ISSUE TITLE
Segmentation fault happened when seg_evict_opt=5 and seg_n_merge=2

### ISSUE THREAD

**Issue by DaokunHu** [Thesys-lab/Segcache#3]
I set the *seg_evict_opt* to 5 (merge fifo) and *seg_n_merge* to 2. Under the workload *c.sbin*,  a **Segment fault** happened with some asserts, shown as below.

[main] assert 'seg_id != -1' failed @ (/home/aim/hdk/test/Segcache/src/storage/seg/seg.c, 177)
[main] assert 'seg->accessible == 0' failed @ (/home/aim/hdk/test/Segcache/src/storage/seg/seg.c, 191)
[main] assert 'seg->evictable == 0' failed @ (/home/aim/hdk/test/Segcache/src/storage/seg/seg.c, 192)
[main] assert 'new_seg->evictable == 0' failed @ (/home/aim/hdk/test/Segcache/src/storage/seg/segmerge.c, 543)
[main] assert 'tb->first_seg_id == old_seg_id' failed @ (/home/aim/hdk/test/Segcache/src/storage/seg/segmerge.c, 163)
[main] assert 'ttl_bucket->last_seg_id == -1' failed @ (/home/aim/hdk/test/Segcache/src/storage/seg/ttlbucket.c, 109)

When I set *seg_n_merge* to 3, Segcache can execute successfully.

**Comment by 1a1a11a** [comment]
Thank you for reporting! Can you run with debug build and gdb? And attach a stacktrace?

**Comment by DaokunHu** [comment]
![image](https://user-images.githubusercontent.com/13998202/148171282-6230b74b-5968-43ad-8e03-ea2d7300cf9d.png)

Here is the patch that triggered this bug.
https://github.com/daokunhu/corner/blob/main/0001-bug.patch


Thanks for your patience!

**Comment by 1a1a11a** [comment]
Thank you! 
It looks like this is not running a debug build (the stack trace is optimized), can you build with `cmake -DCMAKE_BUILD_TYPE=Debug ..` and run with gdb again?

**Comment by DaokunHu** [comment]
Thank you for your reply!
Actually, this is the Debug mode. With <code>make VERBOSE=1</code>, we can see it compiled with <code>-O0 -ggdb3</code>, shown as below.
![image](https://user-images.githubusercontent.com/13998202/148259570-f0e2e0bf-dbcc-4ca2-9564-f8cf496734fa.png)

Besides, thread "1" was traced successfully, shown as below.
![image](https://user-images.githubusercontent.com/13998202/148260485-4cc359fa-b72f-45a1-a692-5a2c40a04b62.png)

It might be a stack overwrite in thread  "segBg", so there were "???" shown in the backtrace.
Would you mind please reproducing the bug by cloning Segcache and applying the patch? May be easier to locate the error in this way.

**Comment by 1a1a11a** [comment]
You are right, I will take a look and get back to you.

**Comment by DaokunHu** [comment]
Hi, is there any clue?

**Comment by 1a1a11a** [comment]
sorry, let me have a look this week. I will try to get back to you ASAP.

**Comment by 1a1a11a** [comment]
I haven't ran into the same overflow problem in your screenshot, but I did fix a bug where the merge stop ratio is incorrect when the number of merged segments is small (for example 2 segments). I have attached the patch, please have a try and let me know. https://gist.github.com/1a1a11a/3cff0dc935089f8dcec58203fe1dd511

**Comment by DaokunHu** [comment]
Thanks, It has solved my problem.
