### ISSUE TITLE
Hi, some questions about scalability?

### ISSUE THREAD

**Issue by Yemaoxin** [Thesys-lab/Segcache#4]
Here is my config:
-----
debug_logging: yes
debug_log_level: 4
trace_path: /home/newstu/Segcache/traces/c.sbin
default_ttl_list: 86400:0.65,1296000:0.27,43200:0.07
heap_mem: 1048576000
hash_power: 26
seg_evict_opt: 2
n_thread:4
seg_n_thread:1
---------

Does it mean that I need to copy four identical files named sbin0, sbin1, sbin2, and sbin3, which have the same content; or do I need to make some division of a sbin file into four files?

**Comment by Yemaoxin** [comment]
Your help is greatly needed

**Comment by 1a1a11a** [comment]
Both are ok, you can have four identical files or four divided files. The processing will treat same object from different traces as different objects.

**Comment by Yemaoxin** [comment]
Thank you!
But I still have a problem.
I used identical files as traces of different threads.
But I don't get higher throughput.

%%%
nthread=1
heap_mem==1GB
%%%
trace_replay_seg.conf total benchmark runtime: 1033.76 s, throughput 4.42 M QPS
average operation latency: 226.34 ns, miss ratio 0.0988
op              get       3818543525(0.8361)
op             gets         97190744(0.0213)
op              set        377823760(0.0827)
op              add        162195118(0.0355)
op              cas         86416393(0.0189)
op           delete         25171345(0.0055)


%%%%
nthread = 2

trace_replay_seg.conf total benchmark runtime: 2513.23 s, throughput 3.47 M QPS
average operation latency: 287.81 ns, miss ratio 0.0665
op              get       7637087052(0.8746)
op             gets        194381488(0.0223)
op              set        850472551(0.0974)
op           delete         50342690(0.0058)
%%%%

%%%%
nthread = 4

trace_replay_seg.conf total benchmark runtime: 8085.75 s, throughput 2.18 M QPS
average operation latency: 457.84 ns, miss ratio 0.0795
op              get      15274174104(0.8649)
op             gets        388762976(0.0220)
op              set       1897062201(0.1074)
op           delete        100685380(0.0057)
%%%%

Could you give a detailed configuration of multi-thread?
Thank you

**Comment by 1a1a11a** [comment]
first you need to set `seg_n_thread` and enable https://github.com/Thesys-lab/Segcache/blob/c9f53a5fb2fc1178179909ba128a8848c00e87be/src/storage/seg/constant.h#L55

**Comment by Yemaoxin** [comment]
yes, I did that.

**Comment by 1a1a11a** [comment]
both of them?

**Comment by 1a1a11a** [comment]
can you paste config?

**Comment by Yemaoxin** [comment]
constant.h
-------
#define USE_THREAD_LOCAL_SEG    2

-------

trace_replay_seg.conf

debug_logging: yes
debug_log_level: 4
#debug_log_file: debug

trace_path: /home/newstu/Segcache/traces/c.sbin
default_ttl_list: 86400:0.65,1296000:0.27,43200:0.07
heap_mem:2097152000
hash_power: 26
seg_evict_opt: 2
n_thread:2
seg_n_thread:1

#datapool_path: /dev/dax1.0
#datapool_name: pmem0

**Comment by 1a1a11a** [comment]
1. set `USE_THREAD_LOCAL_SEG` to 1
2. turn off logging 
3. set `seg_n_thread` to 2 
4. increase hash power to 28 (should not affect much)

**Comment by Yemaoxin** [comment]
OK! Thank you very much!
I will try it again!

**Comment by Yemaoxin** [comment]
Should I set a larger heap_mem?

**Comment by 1a1a11a** [comment]
there is no need to increase `heap_mem`

**Comment by Yemaoxin** [comment]
OK，thank

**Comment by Yemaoxin** [comment]
I'm running that now.
If  I run 4 threads, should I set heap_mem=4GB?
8 threads, set heap_mem=8GB?
or just 1GB

**Comment by 1a1a11a** [comment]
we used same cache size, but both make sense, it depends on your scenario
