### ISSUE TITLE
Questions about the configuration of the experiment

### ISSUE THREAD

**Issue by gwanil** [Thesys-lab/Segcache#5]
I want to experiment with the experiment in Figure 6. To do that, it seems that we need a variety of algo, so do we need to experiment with pelikan? Or should I build this source and benchmark it? Could you tell me how?

I tried building and found trace_replay_* and there were 3 algo in total. (ㄷ(ex.LHD, slab, seg...)

There are six ways in total, what should I do?

**Comment by gwanil** [comment]
I desperately need your help. How do I use PCache and Memcache used in Figure 6? 


I currently know how to do it. 
        [./trace_replay_segtrace_replay_seg.conf]

**Comment by 1a1a11a** [comment]
Hi @gwanil, sorry for the late reply. 
Yes, you can use the trace_replay binary to run the benchmarks 

and what is the problem you have with the config?

**Comment by gwanil** [comment]
There are a total of three trace_replay binaries, and if you look at pictures 6 and 7, there are PCache, Memcache, s-Memcached, r-LHD, r-Hyperbolic, and Segcache, so I want to create a similar graph, how should I experiment? Do I need to download Pelican, too?

**Comment by 1a1a11a** [comment]
you do not need to download Pelikan, the Pelikan bar is trace_replay_slab, Hyperbolic bar is trace_replay_LHD when you change LHD to Hyperbolic in `src/storage/LHD/constant.h`

Memcached code is not included, but you can modify the open-source Memcached to run experiments.
