### ISSUE TITLE
Can I put in another cache algorithm?

### ISSUE THREAD

**Issue by gwanil** [Thesys-lab/Segcache#6]
Hello, I received the explanation of the Fig I answered last time. 

There is one more thing I want to do. I want to add FIFO and LRU to experiment, where should I attach the code and what should I modify?

**Comment by 1a1a11a** [comment]
Yes, you can modify LHD code to support LRU and FIFO. You can add pointers between objects and evict according to the order.

**Comment by gwanil** [comment]
Are you talking about the LHD.h part? Or is it an item or a slab??

Let me ask you a few more questions! 

1. Is cache_size the same as adjusting hip_mem? What is the size unit of heap_mem?
2. Is there an example conf file for LHD? Or are the parameters that should be used when making the config file defined separately?
3. Can I use hyperbolic if I only activate this? 
> https://github.com/Thesys-lab/Segcache/blob/c9f53a5fb2fc1178179909ba128a8848c00e87be/src/storage/LHD/constant.h#L41

**Comment by 1a1a11a** [comment]
what do you mean by `cache_size`?

**Comment by 1a1a11a** [comment]
example config
```
debug_logging: no
debug_log_level: 4

trace_path: /path/to/data
default_ttl_list: 8640000:1

heap_mem: 1048576000
hash_power:26
```

**Comment by gwanil** [comment]
As shown in Figure 6, I would like to know how to adjust cache_size like large cache size and small cache size.

**Comment by 1a1a11a** [comment]
I don't remember it exactly, you can first find the size that it gets compulsory miss ratio, then reduce the size, and choose a large and small cache size.

**Comment by gwanil** [comment]
Could you tell me where to reduce the cache size?

**Comment by gwanil** [comment]
There is one more problem.

This error occurs when you try to build by changing comment to use hyperbolic. Did I correct it wrong?

> https://github.com/Thesys-lab/Segcache/blob/c9f53a5fb2fc1178179909ba128a8848c00e87be/src/storage/LHD/constant.h#L5-L7

![화면 캡처 2022-09-21 121431](https://user-images.githubusercontent.com/55725509/191407168-8affcd06-fdf4-4859-93ea-13be4e4027bc.png)

**Comment by 1a1a11a** [comment]
Hmm, it looks like the code was not cleaned, you need to put LHD related code within macro and change name
you can remove the line in the second error

**Comment by gwanil** [comment]
Yes, I see. I changed it like this and checked that it becomes a build. I think we should test it and see the change of miss raito.

> #define USE_HYPERBOLIC
//#define USE_LHD

>  //   if (!LHD_init) {
 //       init_lhd_class();
 //       LHD_init = true;
//    }

> //    it->ns = ns;

**Comment by gwanil** [comment]
I would appreciate it if you could just tell me how to adjust the cache size

**Comment by 1a1a11a** [comment]
I do not fully understand what you mean by "adjust the cache size", there is heap_mem which is cache size. Are you asking how to choose cache size?

**Comment by gwanil** [comment]
Now I understand if I can change the cache size by changing heap_mem. 
I'm sorry. 

Does heap_mem 1048576000 mean 1G?

**Comment by 1a1a11a** [comment]
yes, technically 1 GiB = 1024 * 1024 * 1024, but yes, I used 1048576000 as 1 GB

**Comment by gwanil** [comment]
I think all the problems have been solved. 
I'm sorry for making you so hard. 

Thank you very much 👍

**Comment by 1a1a11a** [comment]
no problem
