### ISSUE TITLE
Questions about adding LRU and FIFO

### ISSUE THREAD

**Issue by gwanil** [Thesys-lab/Segcache#7]
Hello
You told me that I can modify the LHD code if I want to experiment by adding the LUR and FIFO in the way you answered me last time, so can I modify the code at the location below?

> https://github.com/Thesys-lab/Segcache/blob/NSDI21/src/storage/LHD/LHD.h

I don't know how to modify lru and Fifio well Would you be able to help me?

**Comment by 1a1a11a** [comment]
Yes, but it is not trivial to add FIFO and LRU. :(

**Comment by gwanil** [comment]
Can I get help with the modifications? 😢

**Comment by gwanil** [comment]
I'm currently watching `src/storage/LHD/LHD.h`, so how can I change it? I can't think of a way. 

I don't know if FIFO and LRU should be done the same way as using LHD or Hyper for slabs, or differently.

**Comment by 1a1a11a** [comment]
it will be up to you then, FIFO does not need slab, but LRU does need slab design.

**Comment by gwanil** [comment]
Yes, let me ask you one more question. 

Segments, lhd, and slabs have .c entries.  

What is item.c about? 
(e.g. for use with slabs?)
(e.g., should I use it to make FIFO?)

**Comment by 1a1a11a** [comment]
it is item related
