### ISSUE TITLE
Question about replaying traces

### ISSUE THREAD

**Issue by Jeongseob** [Thesys-lab/Segcache#8]
Hi,

While evaluating the performance of Twitter Memcached, I am wondering whether there is a client-side load generator that can replay the traces. The provided trace replayer is enough for exploring the cache hit and miss ratio. I think, however, it is insufficient for measuring performance numbers such as tail latency because it does not model the inter-arrival rate between requests. 

Thanks in advance!

**Comment by 1a1a11a** [comment]
Do you want to measure the tail latency with the networking stack or just the storage part?

**Comment by Jeongseob** [comment]
I want to measure the latency of Memcached when the underlying memory management is changing. For instance, the operating system can coalesce pages in a contiguous region while Memcached serves requests. To measure the performance of such kinds of techniques, I think the inter-arrival rate between requests should be considered. I prefer to incorporate the time spent on the network stack, but if there is an option to include the storage or memory part, it would be better than the current one.

Thanks,

**Comment by 1a1a11a** [comment]
Pelikan and Memcached pre-allocate all memory during start up, so I do not think there is page coalescing happening. If you want to measure without networking, you can add time measurement to the current implementation and makes the replay following request time (be aware, replaying the full trace takes a week).

**Comment by Jeongseob** [comment]
I meant the technique we are currently developing, not the existing one in the OS. As you mentioned, I could extract the time information and reflect it to the trace. I wondered if there is an already implemented one :)

**Comment by 1a1a11a** [comment]
I do not know any implementation, feel free to add one here if you open source your tool later. :)
